version: '3'

services:
  db:
    image: therealjamesjung/segam-local-db
    restart: always
    ports:
      - '5432:5432'
  backend:
    image: therealjamesjung/segam-local-backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
