name: Deploy to Amazon EC2

on:
  push:
    branches:
      - prod
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_2025_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_2025_AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env file (excluding EC2_PRIVATE_KEY)
        run: |
          # Exclude EC2_PRIVATE_KEY and create .env file from the remaining secrets
          jq -r 'to_entries | map(select(.key != "EC2_PRIVATE_KEY") | "\(.key)=\(.value | tostring)") | .[]' <<< "$SECRETS_CONTEXT" > .prod2025.env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: segam2025
          IMAGE_TAG: latest
        run: |
          # Build a docker container and
          # push it to ECR
          docker build -f prod2025.dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          debug: true
          script: |
            sudo docker rm ${{ secrets.EC2_CONTAINER_NAME }}
            cd ~/actions-runner/_work/segam-backend/segam-backend
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/${{secrets.ECR_REPOSITORY}}:${{secrets.IMAGE_TAG}}
            sudo docker run --name ${{ secrets.EC2_CONTAINER_NAME }} -d -p 3000:3000 --env-file ./.prod2025.env -e TZ=Asia/Seoul -e NODE_ENV=prod ${{ steps.login-ecr.outputs.registry }}/${{secrets.ECR_REPOSITORY}}:${{secrets.IMAGE_TAG}}
